# Compute the total revenue generated by each product (v2ProductName).
SELECT v2ProductName,
       SUM(totalTransactionRevenue) productTotalTransactionRevenue
FROM ecommerce_session_bigquery
GROUP BY v2ProductName
HAVING productTotalTransactionRevenue IS NOT NULL
ORDER BY productTotalTransactionRevenue DESC;

# Determine the total quantity sold for each product.
SELECT v2ProductName,
       SUM(transactions) productTotalTransaction
FROM ecommerce_session_bigquery
GROUP BY v2ProductName
HAVING productTotalTransaction IS NOT NULL
ORDER BY productTotalTransaction DESC;

# Calculate the total refund amount for each product.
WITH ProductRevenue AS (SELECT v2ProductName,
                               COALESCE(SUM(totalTransactionRevenue), 0)                                         AS totalRevenue,
                               COALESCE(SUM(productRefundAmount), 0)                                             AS totalRefund,
                               COALESCE(SUM(totalTransactionRevenue), 0) -
                               COALESCE(SUM(productRefundAmount), 0)                                             AS netRevenue
                        FROM ecommerce_session_bigquery
                        GROUP BY v2ProductName
                        ORDER BY netRevenue DESC)
SELECT v2ProductName,
       totalRevenue,
       totalRefund,
       netRevenue,
       CASE
           WHEN totalRefund > 0.1 * totalRevenue THEN TRUE
           ELSE FALSE
           END AS isMoreThan10Percent
FROM ProductRevenue
ORDER BY netRevenue DESC;